# Generated by Django 5.2.8 on 2025-11-14 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text="La URL pública de tu perfil. Ej: 'la-mejor-manicurista'", max_length=100, unique=True)),
                ('display_name', models.CharField(help_text="El nombre de tu negocio. Ej: 'Manicure Express'", max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Describe brevemente tus servicios.', max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(help_text='Duración total del servicio en minutos. Ej: 45')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio a mostrar (ej: 15000.00)', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Marca si el servicio está activo y se puede agendar')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='booking.professionalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('start_datetime', models.DateTimeField(help_text='Fecha y hora de inicio de la cita')),
                ('end_datetime', models.DateTimeField(help_text='Fecha y hora de fin de la cita (calculada automáticamente)')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmada'), ('CANCELLED_BY_CLIENT', 'Cancelada por Cliente'), ('CANCELLED_BY_PRO', 'Cancelada por Profesional'), ('COMPLETED', 'Completada')], default='CONFIRMED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='booking.professionalprofile')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='booking.service')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Día de la semana')),
                ('start_time', models.TimeField(help_text='Hora de inicio (formato 24h, ej: 09:00)')),
                ('end_time', models.TimeField(help_text='Hora de fin (formato 24h, ej: 17:00)')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='booking.professionalprofile')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
                'unique_together': {('professional', 'weekday', 'start_time', 'end_time')},
            },
        ),
    ]
