# Generated by Django 5.2.8 on 2025-11-21 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Fecha de inicio del bloqueo')),
                ('end_date', models.DateField(help_text='Fecha de fin del bloqueo (puede ser la misma que inicio)')),
                ('description', models.CharField(blank=True, help_text='Ej: Vacaciones, Médico, Feriado', max_length=100)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off', to='booking.professionalprofile')),
            ],
        ),
    ]
