# Generated by Django 5.2.8 on 2025-11-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_timeoff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='client_phone',
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_rut',
            field=models.CharField(default='', max_length=12, verbose_name='RUT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_whatsapp',
            field=models.CharField(default='', max_length=20, verbose_name='WhatsApp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client_email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client_name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
