# Generated by Django 5.2.8 on 2025-11-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_appointment_client_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='client_rut',
            field=models.CharField(default='', max_length=12, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client_whatsapp',
            field=models.CharField(default='', max_length=20, verbose_name='WhatsApp'),
        ),
    ]
