# Generated by Django 5.2.8 on 2026-03-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_appointment_client_rut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(blank=True, help_text='Precio a mostrar (ej: 15000)', null=True),
        ),
    ]
