# Generated by Django 5.2.8 on 2026-05-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Link a tu perfil de Instagram', null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='website_url',
            field=models.URLField(blank=True, help_text='Link a tu sitio web o portafolio', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_datetime',
            field=models.DateTimeField(help_text='Fecha y hora de fin de la cita'),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='end_time',
            field=models.TimeField(help_text='Hora de fin'),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='start_time',
            field=models.TimeField(help_text='Hora de inicio'),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='display_name',
            field=models.CharField(help_text='El nombre de tu negocio.', max_length=100),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='slug',
            field=models.SlugField(blank=True, help_text='La URL pública de tu perfil.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.IntegerField(help_text='Duración total del servicio en minutos.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(blank=True, help_text='Precio a mostrar', null=True),
        ),
        migrations.AlterField(
            model_name='timeoff',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='timeoff',
            name='end_date',
            field=models.DateField(help_text='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='timeoff',
            name='start_date',
            field=models.DateField(help_text='Fecha de inicio'),
        ),
    ]
