# Generated by Django 5.2.8 on 2026-05-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_professionalprofile_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Link a tu página de Facebook', null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Link a tu perfil de LinkedIn', null=True),
        ),
    ]
