# Generated by Django 5.2.8 on 2026-05-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_professionalprofile_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Sube una foto de perfil cuadrada.', null=True, upload_to='profile_pictures/'),
        ),
    ]
