# Generated by Django 5.2.8 on 2026-05-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_professionalprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Si es False, el perfil público mostrará que no está disponible.'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('CANCELLED_BY_CLIENT', 'Cancelada por Cliente'), ('CANCELLED_BY_PRO', 'Cancelada por Profesional'), ('COMPLETED', 'Completada')], default='PENDING', max_length=20),
        ),
    ]
