# Generated by Django 5.2.8 on 2026-05-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_professionalprofile_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Tu número de WhatsApp para contacto.', max_length=20, null=True),
        ),
    ]
