# Generated by Django 5.2.8 on 2026-05-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_professionalprofile_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Básico'), ('PRO', 'Profesional'), ('BUSINESS', 'Business+')], default='FREE', help_text='Plan de suscripción actual.', max_length=20),
        ),
    ]
