# Generated by Django 5.2.8 on 2026-05-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_professionalprofile_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='buffer_time_minutes',
            field=models.IntegerField(default=0, help_text='Minutos de descanso entre citas.'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='lunch_end_time',
            field=models.TimeField(blank=True, help_text='Hora de fin de colación.', null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='lunch_start_time',
            field=models.TimeField(blank=True, help_text='Hora de inicio de colación.', null=True),
        ),
    ]
