# Generated by Django 5.2.8 on 2026-05-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_professionalprofile_buffer_time_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Sube un banner para tu perfil público (Solo PRO).', null=True, upload_to='profile_banners/'),
        ),
    ]
